export const REAL_NAMES = [
  'John Doe',
  'Jane Smith',
  'Michael Johnson',
  'Emily Davis',
  'Chris Brown',
  'Sarah Wilson',
  'David Martinez',
  'Laura Taylor',
  'James Anderson',
  'Emma Thomas',
  'Robert Jackson',
  'Linda White',
  'William Harris',
  'Elizabeth Martin',
  'Richard Thompson',
  'Barbara Garcia',
  'Joseph Martinez',
  'Susan Robinson',
  'Thomas Clark',
  'Jessica Rodriguez',
  'Charles Lewis',
  'Karen Lee',
  'Christopher Walker',
  'Nancy Hall',
  'Daniel Allen',
  'Lisa Young',
  'Matthew Hernandez',
  'Betty King',
  'Anthony Wright',
  'Margaret Lopez',
  'Mark Hill',
  'Sandra Scott',
  'Donald Green',
  'Ashley Adams',
  'Steven Baker',
  'Kimberly Gonzalez',
  'Paul Nelson',
  'Donna Carter',
  'Andrew Mitchell',
  'Carol Perez',
  'Joshua Roberts',
  'Michelle Turner',
  'Kenneth Phillips',
  'Amanda Campbell',
  'Kevin Parker',
];

export const TITLES = [
  'Login Error',
  'Payment Failed',
  'Feature Request',
  'Bug Report',
  'Account Locked',
  'Invoice Issue',
  'API Timeout',
  'UI Glitch',
  'Password Reset',
  'Data Sync Error',
  'Mobile App Crash',
  'Subscription Upgrade',
  'Email Delivery Issue',
  'Integration Error',
  'Performance Lag',
];

export const TAGS_POOL = [
  'bug',
  'feature',
  'billing',
  'account',
  'urgent',
  'ui/ux',
  'mobile',
  'api',
  'security',
  'data',
];

export const CUSTOMER_MESSAGES = [
  'I am facing this issue since morning.',
  'Can you please look into this ASAP?',
  'Here is the screenshot you asked for.',
  'Is there any update? It is critical for us.',
  'I tried clearing the cache but it did not work.',
  'This happens every time I click the export button.',
  'Thanks, that solved the problem!',
  'I am still getting a 500 error.',
  'How do I change my billing address?',
];

export const AGENT_MESSAGES = [
  'I am looking into this issue right now.',
  'Could you please provide a screenshot of the error?',
  'I have escalated this to the technical team.',
  'Please try clearing your browser cache and cookies.',
  'We have released a fix, please refresh the page.',
  'Could you please verify your account email?',
  'I apologize for the inconvenience.',
  'This feature is available in the settings menu.',
  'Let me check the server logs for you.',
];
